#!/usr/bin/env python

import sys
import g4f
from termcolor import colored
from rich.console import Console
from rich.markdown import Markdown
import time

console = Console()

# flags
g4f.debug.version_check = False
is_raw = '--raw' in sys.argv
has_file = not sys.stdin.isatty()

linux_expert = """
    Imagine you are an expert Linux, Bash scripting, JavaScript, Python and related fields.
    I will ask you questions related this area and expect for your help.
    Please answer as short as possible, do not include unneeded details to your answer.
    Omit surplus unnecessary text, concentrate on code examples.
"""

def generate_response(prompt: str) -> str:
    start_time = time.time()
    response = g4f.ChatCompletion.create(
        model=g4f.models.gpt_35_turbo_16k_0613,
        messages=[{"role": "user", "content": prompt}],
    )
    end_time = time.time()
    print(colored(f"GPT answer took {(end_time - start_time):.2f} seconds", "grey"))
    return response

file = ""
if has_file:
    file = "".join([line for line in sys.stdin])


user_input = ' '.join(sys.argv[1:])

if is_raw:
    prompt = file
    prompt += user_input
else:
    prompt = linux_expert
    if has_file:
        prompt += f"""
        I have a file:
        {file}

        """
    prompt += f"""
        My question is: {user_input}
    """

print(colored(user_input, "magenta"))
# print(prompt)

response = generate_response(prompt)


md = Markdown(response)
console.print(md)
